// <auto-generated />
using AndrewDAL.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AndrewDAL.Migrations
{
    [DbContext(typeof(SqLiteContext))]
    [Migration("20250210085856_SkillAndExp")]
    partial class SkillAndExp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("AndrewDAL.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("Password")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            Login = "admin",
                            Password = "admin"
                        });
                });

            modelBuilder.Entity("AndrewDAL.Models.CmsSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CmsSectionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CmsSectionTypeId");

                    b.HasIndex("ImageId");

                    b.ToTable("CmsSections");
                });

            modelBuilder.Entity("AndrewDAL.Models.CmsSectionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CmsSectionTypes");
                });

            modelBuilder.Entity("AndrewDAL.Models.ContactForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailPlaceholder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessagePlaceholder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePlaceholder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitlePlaceholder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailLabel = "Email",
                            EmailPlaceholder = "Enter your email",
                            MessageLabel = "Message",
                            MessagePlaceholder = "Enter your message",
                            NameLabel = "Name",
                            NamePlaceholder = "Enter your name",
                            TitleLabel = "Title",
                            TitlePlaceholder = "Enter the title"
                        });
                });

            modelBuilder.Entity("AndrewDAL.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("AndrewDAL.Models.VisitorMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VisitorMessages");
                });

            modelBuilder.Entity("AndrewDAL.Models.CmsSection", b =>
                {
                    b.HasOne("AndrewDAL.Models.CmsSectionType", "CmsSectionType")
                        .WithMany("CmsSections")
                        .HasForeignKey("CmsSectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AndrewDAL.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmsSectionType");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("AndrewDAL.Models.CmsSectionType", b =>
                {
                    b.Navigation("CmsSections");
                });
#pragma warning restore 612, 618
        }
    }
}
